repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        exclude: "(^|/)migrations/"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "(^|/)migrations/"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "(^|/)migrations/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: "(^|/)migrations/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: "(^|/)migrations/"
      - id: trailing-whitespace
        exclude: "(^|/)migrations/"
      - id: check-yaml
        exclude: "(^|/)migrations/"
      - id: check-merge-conflict
      - id: detect-private-key
